- name: setup
  hosts: localhost
  connection: local
  vars:
    brew_pkgs:
      - tree
      - git
      - gh
      - jq
      - watchman
      - zsh-autosuggestions
      - zsh-completions
      - zsh-syntax-highlighting
      - awscli
      - anyenv
    brew_cask_apps:
      - adoptopenjdk8
      - google-japanese-ime
      - karabiner-elements
      - react-native-debugger
      - visual-studio-code
  tasks:
    - name: Install First Homebrew
      shell: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

    - name: Update homebrew itself first
      homebrew: update_homebrew=yes

    - name: Install brew pkg
      homebrew: name {{ item }}
      with_items: "{{ brew_pkgs }}"

    - name: Install application
      homebrew_cask:
        name: "{{ item }}"
        state: "present"
        install_options: "appdir=/Applications"
        accept_external_apps: yes
      with_items: "{{ brew_cask_apps }}"
